---
- hosts: localhost
  become: yes

  vars_files:
    - {{ lookup('env','HOME') }}/vars.yml

  roles:
    - role: whiskerlabs.ssh-config
    - role: manala.zsh
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
        
    - name: Install dtrx
      apt:
        name: dtrx
        state: present
        
    - name: Install zsh-autosuggestions
      apt:
        name: zsh-autosuggestions
        state: present
        

      
