---
- hosts: localhost
  gather_facts: yes
  become: yes

  vars_files:
    - "{{ lookup('env','HOME') }}/vars.yml"

  roles:
    #- role: robertdebock.git
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
    
    - name: Install zsh
      apt:
        name: zsh
        state: present
    
    - name: Install zsh-antigen
      apt:
        name: zsh-antigen
        state: present
        
    - name: Create zsh config file
      file:
        path: "{{ lookup('env','HOME') }}/.zshrc"
        state: touch
        mode: u=rw,g=r,o=r
          
    - name: Populate zsh config file
      blockinfile:
        path: "{{ lookup('env','HOME') }}/.zshrc"
        block: |
          source /usr/share/zsh-antigen/antigen.zsh
          antigen use oh-my-zsh
          antigen bundle history
          antigen bundle extract
          antigen bundle twang817/zsh-ssh-agent
          antigen bundle zsh-users/zsh-syntax-highlighting
          antigen bundle zsh-users/zsh-autosuggestions
          antigen theme robbyrussell
          antigen apply
        state: present
        
    - name: Create ssh config file
      file:
        path: "{{ lookup('env','HOME') }}/.ssh/config"
        state: touch
        mode: u=rw,g=r,o=r
          
    - name: Populate zsh config file
      blockinfile:
        path: "{{ lookup('env','HOME') }}/.ssh/config"
        block: "{{ssh_config}}"
        state: present    
    
    - name: Create git config file
      file:
        path: "{{ lookup('env','HOME') }}/.gitconfig"
        state: touch
        mode: u=rw,g=r,o=r
          
    - name: Populate git config file
      blockinfile:
        path: "{{ lookup('env','HOME') }}/.gitconfig"
        block: "{{git_config}}"
        state: present    
