---
- hosts: localhost
  become: yes

  vars_files:
   - /home/mitchac/vars.yml

  roles:
    - role: whiskerlabs.ssh-config
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
        
    - name: Install dtrx
      apt:
        name: dtrx
        state: present
        
    - name: Install fish
      apt:
        name: fish
        state: present
