---
- hosts: localhost
  become: yes

  roles:
    - role: whiskerlabs.ssh-config
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
        
    - name: Install dtrx
      apt:
        name: dtrx
        state: present
        
    - name: Install fish
      apt:
        name: fish
        state: present
        
    - name: Install fundle
      shell: |
        curl -sfL https://git.io/fundle-install | fish
      
    - name: Create fish config file
      file:
        path: "{{home}}/.config/fish/config.fish"
        state: touch
        mode: u=rw,g=r,o=r
      become: true
      become_method: sudo
      become_user: "{{account}}"
