---
- hosts: localhost
  become: yes

  vars_files:
    - "{{ lookup('env','HOME') }}/vars.yml"

  roles:
    - role: whiskerlabs.ssh-config
    #- role: manala.zsh
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
    
    - name: Install zsh
      apt:
        name: zsh
        state: present
    
    - name: Install zsh-antigen
      apt:
        name: zsh-antigen
        state: present
        
    - name: Create zsh config file
      file:
        path: "{{ lookup('env','HOME') }}/.zshrc"
        state: touch
        mode: u=rw,g=r,o=r
          
    - name: Populate zsh config file
      blockinfile:
        path: "{{ lookup('env','HOME') }}/.zshrc"
        block: |
          source /usr/share/zsh-antigen/antigen.zsh
          antigen use oh-my-zsh
          antigen bundle history
          antigen bundle extract
          antigen bundle zsh-users/zsh-syntax-highlighting
          antigen bundle zsh-users/zsh-autosuggestions
          antigen theme robbyrussell
          antigen apply
        state: present
