---
- hosts: localhost
  become: yes

  vars_files:
   - /home/debian/vars.yml

  roles:
    - role: robertdebock.git
    - role: whiskerlabs.ssh-config
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
        
    - name: Install sshfs
      apt:
        name: sshfs
        state: present
