---
- hosts: localhost
  become: yes

  vars_files:
   - /home/debian/vars.yml

  roles:
    - role: robertdebock.git
    - role: whiskerlabs.ssh-config
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
        
    - name: Install snapd
      apt:
        name: snapd
        state: present
        
    - name: Install croc
      community.general.snap:
        name: croc
        state: present
   
