---
- hosts: localhost
  become: yes

  vars_files:
   - /home/debian/vars.yml

  roles:
    - role: robertdebock.git
    - role: whiskerlabs.ssh-config
    
  tasks:
    - name: Install neovim
      apt:
        name: neovim
        state: present
 
 # Install croc and deps
    - name: Install snapd and deps
      apt:
        pkg:
        - snapd
        - libsquashfuse0    
        - squashfuse
        - fuse
                
    - name: Install croc
      community.general.snap:
        name: croc
        state: present
   
